### PR TITLE
Scala Center website redesign 

### PR DESCRIPTION
**Pull request by dominv**
This PR contains a changes related to design, layouts and responsive support. We've been coordinating with Heather and the rest of the Scala Center team during the different stages of this work, receiving feedback from their end from wireframe design to the actual implementation in Jekyll.

The changes are mainly focused in the HTML code and CSS styles although new information, specially related with Scala Center's **Projects** and **Team**, has been added too. 

- The **Home**  page has been fully redesigned to present the information in a clearer and more structured way, giving special importance to the **Scala Center's Projects** and to the hard work developed by the **Scala Center's Engineers.**

- Two new pages has been created:
  - **Projects** page contains all the information related with the Scala Center's projects including links to their repositories, websites and origin as well as a list of the team members that have contributed to each project. 
  - **Team** page includes all the Scala Center's members information including the projects they can be contacted for. 

- The **topbar** now shows all the website's pages.

The new data added is distributed in the three following folders:

- **_projects** : Contains all the information about the different projects, each one of them in its own markdown file that includes, among other fields, a list of contributors and an optional small description as well as a wider content. 
- **_contact** : In this directory there can be found some other Scala Center team’s activities, each one of them, in its own markdown file but, in this case, with a much more simple structure.
- **_ data** : There are two `yaml` files in this directory:
  - **education.yml** : Includes the home page education section’s data.
  - **team-members** : This file contains the information about all the team’s members including the projects or activities to contact for and the projects their currently working on with the appropriate percentage.
 
@heathermiller could you please review it?

Thanks!

### CODE REVIEW

**Comment by heathermiller** [comment]
❤️

**Comment by heathermiller** [comment]
Optimistically merging – us at the Scala Center can update percentages etc on our own. Thank you so much @dominv!! ❤️ ❤️

**Comment by heathermiller** [comment]
Hey @dominv it seems we're missing something. Seems there's a hardcoded path here to font-awesome that fails the build:

```
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'resources/css/main.scss':
                    File to import not found or unreadable: ../../../bower_components/font-awesome/scss/font-awesome. Load path: /Users/hmiller/Dropbox/git-shared/scala.epfl.ch/resources/css/sass on line 5
```

Here's the Travis build (in the repo that we deploy) ([PR](https://github.com/scala/scala.epfl.ch/pull/18)): 
https://travis-ci.org/scala/scala.epfl.ch/builds/231608252?utm_source=github_status&utm_medium=notification

Seems it's this line in the `_base.scss` file:
```sass
@import "../../../bower_components/font-awesome/scss/font-awesome";
```

Can we include these files in the `resources` folder and update this path accordingly?

**Comment by dominv** [comment]
Hey @heathermiller, I've just made a small PR to fix this issue https://github.com/scalacenter/scala.epfl.ch/pull/6

**Pull request merged**
